<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-07 at 20:28:16.
 */
use PHPUnit\Framework\TestCase;
require "../../classes/Validation.php";
class ValidationTest extends TestCase {

    /**
     * @var Validation
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Validation;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Validation::validate
     * @dataProvider dataSet
     */
    public function testValidate($input, $regex,$valid) {
        try {
            Validation::validate($input, $regex);
            $this->assertTrue($valid, 'The input is valid');
        } catch (Exception $ex) {
            $this->assertTrue(!$valid, 'The input is invalid');
        }
        
    }
    function dataSet(){
        return [
        // Name
        'Test Name 1'=>     ["a",           Validation::NAME,       FALSE],
        'Test Name 2'=>     ["ab",          Validation::NAME,       FALSE],
        'Test Name 3'=>     ["abc",         Validation::NAME,       TRUE],
        'Test Name 4'=>     ["abc def",     Validation::NAME,       TRUE],
        'Test Name 5'=>     ["",            Validation::NAME,       FALSE],
            
        // Email
        'Test Email 1'=>    ["a",           Validation::EMAIL,       FALSE],
        'Test Email 2'=>    ["ab",          Validation::EMAIL,       FALSE],
        'Test Email 3'=>    ["abc@a",       Validation::EMAIL,       FALSE],
        'Test Email 4'=>    ["ab@a.com",    Validation::EMAIL,       TRUE],
        'Test Email 5'=>    ["",            Validation::EMAIL,       FALSE],
        'Test Email 6'=>    ["@a.com",      Validation::EMAIL,       FALSE],
        'Test Email 7'=>    ["a@.com",      Validation::EMAIL,       FALSE],
            
        // Date
        'Test Date 1'=>    ["a",            Validation::DATE,       FALSE],
        'Test Date 2'=>    ["04",           Validation::DATE,       FALSE],
        'Test Date 3'=>    ["04/14",        Validation::DATE,       FALSE],
        'Test Date 4'=>    ["04/14/2016",   Validation::DATE,       TRUE],
        'Test Date 5'=>    ["",             Validation::DATE,       FALSE],
        'Test Date 6'=>    ["4/01/2016",    Validation::DATE,       TRUE],
        'Test Date 7'=>    ["4/1/2016",     Validation::DATE,       TRUE],
        'Test Date 8'=>    ["104/01/2016",  Validation::DATE,       FALSE],
        'Test Date 9'=>    ["4/101/2016",   Validation::DATE,       FALSE],
        'Test Date 10'=>   ["04/01/12016",  Validation::DATE,       FALSE],
            
        // Time
        'Test Time 1'=>    ["",             Validation::TIME,       FALSE],
        'Test Time 2'=>    ["1",            Validation::TIME,       FALSE],
        'Test Time 3'=>    ["03:70",        Validation::TIME,       FALSE],
        'Test Time 4'=>    ["10:55",        Validation::TIME,       TRUE],
        'Test Time 5'=>    ["22:30",        Validation::TIME,       TRUE],
            
        ];
    }

}
